### ISSUE TITLE
Option to send email not appearing on iOS 12.1.2 (16C101)

### ISSUE THREAD

**Issue by m52go** [joachimneumann/bisqremote_iOS#2] opened 2018-12-23 02:57 UTC
Just got this feedback [on Twitter](https://twitter.com/ElkimXOC/status/1076609455687716865).

**Comment by moneroproblem** [comment] 2018-12-30 08:16
Hi,
I could not reproduce this bug, also running iOS 12.1.2 (16C101). Could you attach a screenshot of the missing option to send the email?

Thanks - Joachim

**Comment by joachimneumann** [comment] 2018-12-30 09:13
When testing on iOS 12.1.2 (16C101), I had the option to send an email with the pairing token and I could also send and receive the email. May be the problem is that the pairing did not happen after pasting the token into Bisq. I will investigate further.

**Comment by devinbileck** [comment] 2019-11-09 00:58
Perhaps it is caused by the default mail app not configured?
I suspect it may be this line:
https://github.com/joachimneumann/bisqremote_iOS/blob/master/bisqremote/EmailViewController.swift#L38
In any case, it needs better error reporting.

**Comment by josibake** [comment] 2020-10-21 22:43
can confirm, this will not work unless the default mail app on ios is installed. without the default mail, there was no pop up screen or token in the bisq app to send. after i installed the mail app, it did pull up an email with the token in the mail app

**Comment by devinbileck** [comment] 2021-04-23 20:25
This should be resolved with the following commit: https://github.com/bisq-network/bisqremote_iOS/pull/7/commits/3880ed89bf2e0ba993d6a5e0416ff96e99c5a9a6
And will be available in v1.2.

**Closed as completed by devinbileck** 2021-04-23 20:25 UTC
