### ISSUE TITLE
Can't pair Bisq on iOS

### ISSUE THREAD

**Issue by cocaesprit** [joachimneumann/bisqremote_iOS#6] opened 2021-02-26 13:53 UTC
Running v1.5.6 on Linux and Bisq mobile on iOS 14. When trying to connect, either with QR or manually with the pairing token, nothing happens. I should provide more details, I know, I just don't know where to start, let me know!

**Comment by devinbileck** [comment] 2021-04-23 20:28
Sounds like a duplicate of #2 
Should be resolved in v1.2.

**Closed as completed by devinbileck** 2021-04-23 20:28 UTC
